const fetch = require('node-fetch');

async function test() {
  const longUrl = "https://labforge.baladev.me/?share=eyJkb2NJbmZvIjp7ImNvdXJzZUZ1bGxUaXRsZSI6IjE5QUk0MTEtTmV1cmFsIE5ldHdvcmtzIiwic3R1ZGVudE5hbWUiOiJEQUtTSElOQSBNT09SVEhZIE4gRCIsInJlZ2lzdGVyTnVtYmVyIjoiMjEyMjI0MjMwMDQ5In0sImV4cGVyaW1lbnRzIjpbeyJpZCI6ImUyZGE0ZjlhLThiY2UtNDcwYS05MWVmLTNlYTYwZTJhOTMyYyIsInNlcmlhbE5vIjoxLCJ0aXRsZSI6IkludHJvZHVjdGlvbiB0byBLYWdnbGUgJiBEYXRhIHByZXByb2Nlc3NpbmcgQ29tcGxldGlvbiByZXF1aXJlbWVudHMiLCJkYXRlIjoiMjAyNi0wMS0yOSIsImdpdGh1YkxpbmsiOiJodHRwczovL2dpdGh1Yi5jb20vbmRkYWtzaGluYW1vb3J0aHkwNy9FeC0xLU5OLmdpdCJ9LHsiaWQiOiJkNzQ0NzRiMy0zYjQxLTRmYTktYjQyOC1hNGViMzk1OTRmMjUiLCJzZXJpYWxObyI6MiwidGl0bGUiOiJJbXBsZW1lbnRhdGlvbiBvZiBQZXJjZXB0cm9uIGZvciBiaW5hcnkgY2xhc3NpZmljYXRpb24iLCJkYXRlIjoiMjAyNi0wMi0xMiIsImdpdGh1YkxpbmsiOiJodHRwczovL2dpdGh1Yi5jb20vbmRkYWtzaGluYW1vb3J0aHkwNy9FeC0yLS1OTi5naXQifSx7ImlkIjoiZGI5ZDc4M2EtMGJlMS00ODkxLTg1YmItM2JjM2JhYWUxZDNlIiwic2VyaWFsTm8iOjMsInRpdGxlIjoiSW1wbGVtZW50YXRpb24gb2YgTUxQIGZvciBOb24tbGluZWFybHkgc2VwZXJhYmxlIGRhdGEiLCJkYXRlIjoiMjAyNi0wMi0xOSIsImdpdGh1YkxpbmsiOiJodHRwczovL2dpdGh1Yi5jb20vbmRkYWtzaGluYW1vb3J0aHkwNy9FeC0zLU5OLmdpdCJ9LHsiaWQiOiIwY2Q4MGFmMC00ZTUwLTQ2OTgtYmRhMC04ODc2MDI1N2M4YzEiLCJzZXJpYWxObyI6NCwidGl0bGUiOiJJbXBsZW1lbnRhdGlvbiBvZiBNdWx0aS1MYXllciBQZXJjZXB0cm9uIGZvciBNdWx0aWNsYXNzaWZpY2F0aW9uIiwiZGF0ZSI6IjIwMjYtMDItMjYiLCJnaXRodWJMaW5rIjoiaHR0cHM6Ly9naXRodWIuY29tL25kZGFrc2hpbmFtb29ydGh5MDcvRXgtNC1OTi5naXQifSx7ImlkIjoiOTM1OTYzZGQtZTA4NC00ZmY0LWI1MTctMTg1ZjE4MmEwMDQ1Iiwic2VyaWFsTm8iOjUsInRpdGxlIjoiSW1wbGVtZW50YXRpb24gb2YgWE9SIHVzaW5nIFJCRk5OIiwiZGF0ZSI6IjIwMjYtMDMtMTIiLCJnaXRodWJMaW5rIjoiaHR0cHM6Ly9naXRodWIuY29tL25kZGFrc2hpbmFtb29ydGh5MDcvRXgtNS0tTk4vYmxvYi9tYWluL1JFQURNRS5tZCJ9LHsiaWQiOiIyOTU0Mzg1Zi1kMTAyLTRiYmYtOTliYi1jYzBiZjBjMmM0MDMiLCJzZXJpYWxObyI6NiwidGl0bGUiOiJIZWFydCBhdHRhY2sgcHJlZGljdGlvbiB1c2luZyBNTFAiLCJkYXRlIjoiMjAyNi0wMy0xNyIsImdpdGh1YkxpbmsiOiJodHRwczovL2dpdGh1Yi5jb20vbmRkYWtzaGluYW1vb3J0aHkwNy9FWC02LU5OLmdpdCJ9XX0";
  try {
    const res = await globalThis.fetch("https://tinyurl.com/api-create.php?url=" + encodeURIComponent(longUrl));
    const text = await res.text();
    console.log("Result:", text);
  } catch (e) {
    console.error(e);
  }
}

test();
